server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#设置feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  #建立连接后从后台服务器 读取到可用资源所需时间
  ReadTimeout: 3000
  #建立链接使用的时间
  ConnectTimeout: 3000
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型      #mysql驱动包
      url: jdbc:mysql://localhost:3306/db2019?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
feign: # 熔断降级开启 针对客户服务
  hystrix:
    enabled: true