server:
  port: 8001

spring:
  application:
    name: cloud-provider-service  #提供者名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型      #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imut.springcloud.entities       #所有Entity别名类所在包
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka , http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径显示ip地址
    lease-expiration-duration-in-seconds: 5  #服务端在接收最后一次心跳后超过预定时间，超时则剔除（默认90s）
    lease-renewal-interval-in-seconds: 2 #客户端向服务端发送心跳得时间间隔（默认30s）