spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/assist?&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 123456
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 1000

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名

server:
  tomcat:
    connection-timeout: 18000000

user:
  defultMoney: 3000