eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    #启用服务消费者从注册中心拉取服务列表的功能
    fetch-registry: true
    #service-url:
     # defaultZone: http://eureka7002.com:7002/eureka  集群环境 互相注册
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #单机环境注册自己
  server:
    #关闭自我保护措施 保证不可用的服务被及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
server:
  port: 7001
