server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型      #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     # defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka 集群版
      defaultZone: http://eureka7001.com:7001/eureka #单机版