spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/assist?&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 123456
  redis:
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8  #链接池最大连接数
        max-idle: 0 #设置最大空闲连接数
    timeout: 30000

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名

user:
  name:
    ygw: 666